#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 19 09:49:15 2022

@author: iliana
"""

# This program creates a file to download, using wget, the PDF versions 
# of the spectra generated by Rakshit et al. from 
# https://seafile.utu.fi/d/9866433c200743119e92/?p=%2F

import numpy as np
from astropy.io import ascii

filename = "DR14Q_nonDetected_CIV"
# filename = "DR14Q_psDetected_CIV"
# filename = "DR14Q_nonDetected_MgII"
# filename = "DR14Q_psDetected_MgII"



# plate, mjd, fiber = np.loadtxt(filename+'.txt', unpack=True, skiprows=1)

data = ascii.read(filename+'.txt')

plate = data['PLATE']
mjd = data['MJD']
fiber = data['FIBERID']

plate_range_low = np.zeros(len(plate))
for i in range(len(plate)):
    if plate[i] < 1000:
        plate_range_low[i] = 0
    elif plate[i] < 2000:
        plate_range_low[i] = 1000
    elif plate[i] < 3000:
        plate_range_low[i] = 2000
    elif plate[i] < 4000:
        plate_range_low[i] = 3000
    elif plate[i] < 5000:
        plate_range_low[i] = 4000
    elif plate[i] < 6000:
        plate_range_low[i] = 5000
    elif plate[i] < 7000:
        plate_range_low[i] = 6000
    elif plate[i] < 8000:
        plate_range_low[i] = 7000
    elif plate[i] < 9000:
        plate_range_low[i] = 8000
    elif plate[i] < 10000:
        plate_range_low[i] = 9000
    elif plate[i] == 10000:
        plate_range_low[i] = 1000

plate_range_high = np.zeros(len(plate))
for i in range(len(plate)):
    if plate[i] < 1000:
        plate_range_high[i] = 999
    elif plate[i] < 2000:
        plate_range_high[i] = 1999
    elif plate[i] < 3000:
        plate_range_high[i] = 2999
    elif plate[i] < 4000:
        plate_range_high[i] = 3999
    elif plate[i] < 5000:
        plate_range_high[i] = 4999
    elif plate[i] < 6000:
        plate_range_high[i] = 5999
    elif plate[i] < 7000:
        plate_range_high[i] = 6999
    elif plate[i] < 8000:
        plate_range_high[i] = 7999
    elif plate[i] < 9000:
        plate_range_high[i] = 8999
    elif plate[i] < 10000:
        plate_range_high[i] = 9999



plate = plate.astype(int).astype(str)
mjd = mjd.astype(int).astype(str)
fiber = fiber.astype(int).astype(str)
plate_range_low = plate_range_low.astype(int).astype(str)
plate_range_high = plate_range_high.astype(int).astype(str)


plate_f = np.char.zfill(plate, 4)
mjd_f = np.char.zfill(mjd, 5)
fiber_f = np.char.zfill(fiber, 4)
plate_low_f = np.char.zfill(plate_range_low, 4)
plate_high_f = np.char.zfill(plate_range_high, 4)


file_object = open('WGET_'+filename+'.txt', 'w')
# server = "https://seafile.utu.fi/d/9866433c200743119e92/files/?p=%2FPlots%2Fplate"
server = "https://seafile.utu.fi/d/9866433c200743119e92/files/?p=%2Fmodel%2Fplate"



for i in range(len(plate_f)):
    file_object.write('wget -O '+plate_f[i]+'-'+mjd_f[i]+'-'+fiber_f[i]+'.fits '\
                      +'"'+server+'_'+plate_low_f[i]+'_'+plate_high_f[i]+'%2F'+\
                      plate[i]+'%2F'+plate_f[i]+'-'+mjd_f[i]+'-'+fiber_f[i]+\
                          '_model.fits&dl=1"\n')
file_object.close()
        

file_list = open ('list'+filename+'.txt', 'w')

for i in range(len(plate_f)):
    file_list.write(plate_f[i]+'-'+mjd_f[i]+'-'+fiber_f[i]+'.fits\n')
file_list.close()
